services:
  - type: web
    name: traffic-monitoring-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: WORKERS
        value: 4
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
    plan: free 